# Generated by Django 4.2.3 on 2023-07-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="dealer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stock.dealer"
            ),
        ),
    ]
