# Generated by Django 4.2.3 on 2023-07-09 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_warehouse_dealer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dealer",
            old_name="user",
            new_name="owner",
        ),
    ]
