# Generated by Django 4.2.2 on 2023-07-03 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pan', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(max_length=70)),
            ],
        ),
    ]
